name: subscription_tracker
description: Subscription tracker for Streams.
version: 1.0.1
repository: https://github.com/olostan/subscription_tracker

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
#dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
